# Generated by Django 2.2.3 on 2019-07-25 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_cours_org'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='cours_org',
            new_name='course_org',
        ),
    ]
