# Generated by Django 2.2.3 on 2019-07-25 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20190725_0947'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_classic',
            field=models.BooleanField(default=False, verbose_name='是否经典'),
        ),
    ]
