# Generated by Django 2.2.3 on 2019-08-08 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_auto_20190808_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='url',
            field=models.CharField(max_length=200, verbose_name='访问地址'),
        ),
    ]
